# Generated by Django 2.1.7 on 2019-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apidata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.CharField(blank=True, max_length=200, null=True)),
                ('start_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('end_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('total_time', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('image_sources', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
